/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/yucca.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useCharacterAnimations } from '../contexts/CharacterAnimations'

const Yucca = (props) => {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/yucca.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { setAnimations, animationIndex } = useCharacterAnimations()
  const { actions, names } = useAnimations(animations, group)
  console.log(names)

  useEffect(() => {
    setAnimations(names)
  }, [names])

  useEffect(() => {
    actions[names[animationIndex]].reset().fadeIn(0.5).play()
    return () => {
      actions[names[animationIndex]].fadeOut(0.5)
    }
  }, [animationIndex])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature002" position={[0, 0, -0.02]} scale={0.753}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone005} />
          <primitive object={nodes.Bone008} />
          <skinnedMesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Material.050']} skeleton={nodes.Sphere001.skeleton} />
          <skinnedMesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Material.068']} skeleton={nodes.Sphere002.skeleton} />
          <skinnedMesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={materials['Material.048']} skeleton={nodes.Sphere003.skeleton} />
          <skinnedMesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={materials['Material.051']} skeleton={nodes.Sphere004.skeleton} />
          <skinnedMesh name="Sphere024" geometry={nodes.Sphere024.geometry} material={materials['Material.074']} skeleton={nodes.Sphere024.skeleton} />
        </group>
        <group name="Sphere010" position={[-0.051, 1.377, 0.569]} rotation={[-0.687, 0.238, 0.197]} scale={0.271}>
          <mesh name="Sphere027" geometry={nodes.Sphere027.geometry} material={materials['Material.047']} />
          <mesh name="Sphere027_1" geometry={nodes.Sphere027_1.geometry} material={materials['Material.049']} />
          <mesh name="Sphere027_2" geometry={nodes.Sphere027_2.geometry} material={materials['Material.053']} />
          <mesh name="Sphere027_3" geometry={nodes.Sphere027_3.geometry} material={materials['Material.054']} />
          <mesh name="Sphere027_4" geometry={nodes.Sphere027_4.geometry} material={materials['Material.055']} />
          <mesh name="Sphere027_5" geometry={nodes.Sphere027_5.geometry} material={materials['Material.056']} />
          <mesh name="Sphere027_6" geometry={nodes.Sphere027_6.geometry} material={materials['Material.057']} />
          <mesh name="Sphere027_7" geometry={nodes.Sphere027_7.geometry} material={materials['Material.058']} />
          <mesh name="Sphere027_8" geometry={nodes.Sphere027_8.geometry} material={materials['Material.059']} />
          <mesh name="Sphere027_9" geometry={nodes.Sphere027_9.geometry} material={materials['Material.060']} />
          <mesh name="Sphere027_10" geometry={nodes.Sphere027_10.geometry} material={materials['Material.061']} />
          <mesh name="Sphere027_11" geometry={nodes.Sphere027_11.geometry} material={materials['Material.062']} />
          <mesh name="Sphere027_12" geometry={nodes.Sphere027_12.geometry} material={materials['Material.063']} />
          <mesh name="Sphere027_13" geometry={nodes.Sphere027_13.geometry} material={materials['Material.064']} />
          <mesh name="Sphere027_14" geometry={nodes.Sphere027_14.geometry} material={materials['Material.065']} />
          <mesh name="Sphere027_15" geometry={nodes.Sphere027_15.geometry} material={materials['Material.066']} />
          <mesh name="Sphere027_16" geometry={nodes.Sphere027_16.geometry} material={materials['Material.067']} />
        </group>
      </group>
    </group>
  )
}

export default Yucca

useGLTF.preload('./models/yucca.glb')
