/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/yucca.glb 
*/

import React, { useEffect } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';
import { useCharacterAnimations } from '../contexts/CharacterAnimations';

const Yucca = (props) => {
  const group = React.useRef();
  const { scene, animations } = useGLTF('/models/yucca.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { setAnimations, animationIndex } = useCharacterAnimations();
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    setAnimations(names);
  }, [names, setAnimations]);

  useEffect(() => {
    Object.values(actions).forEach((action) => {
      action.stop();
    });
    
    const currentAction = actions[names[animationIndex]];
    if (currentAction) {
      currentAction.timeScale = animationIndex === 1 ? 2.0 : 1.0;
      currentAction.reset().fadeIn(0.5).play();
    }

    return () => {
      if (currentAction) {
        currentAction.fadeOut(0.5);
      }
    };
  }, [animationIndex, actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Main" position={[0.728, 1.135, 4.12]} scale={0.855}>
          <primitive object={nodes.root} />
          <primitive object={nodes.ControlLips} />
          <primitive object={nodes.neutral_bone} />
          <mesh name="Sphere005" geometry={nodes.Sphere005.geometry} material={materials.Teeth} position={[-0.97, -0.543, -2.266]} rotation={[-0.668, 0.107, 0.09]} scale={0.318} />
          <skinnedMesh name="Headd001" geometry={nodes.Headd001.geometry} material={materials['Material.067']} skeleton={nodes.Headd001.skeleton} morphTargetDictionary={nodes.Headd001.morphTargetDictionary} morphTargetInfluences={nodes.Headd001.morphTargetInfluences} />
        </group>
        <group name="Armature003" position={[0, 0.025, 4.076]} scale={0.753}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone005} />
          <primitive object={nodes.Bone008} />
          <skinnedMesh name="Sphere013" geometry={nodes.Sphere013.geometry} material={materials['Material.074']} skeleton={nodes.Sphere013.skeleton} />
          <skinnedMesh name="Sphere014" geometry={nodes.Sphere014.geometry} material={materials['Material.050']} skeleton={nodes.Sphere014.skeleton} />
          <skinnedMesh name="Sphere015" geometry={nodes.Sphere015.geometry} material={materials['Material.068']} skeleton={nodes.Sphere015.skeleton} />
          <skinnedMesh name="Sphere016" geometry={nodes.Sphere016.geometry} material={materials['Material.048']} skeleton={nodes.Sphere016.skeleton} />
          <skinnedMesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials['Material.051']} skeleton={nodes.Sphere017.skeleton} />
        </group>
        <group name="Sphere012" position={[-0.133, 1.423, 4.667]} rotation={[-0.66, 0.072, 0.056]} scale={0.271}>
          <mesh name="Sphere011" geometry={nodes.Sphere011.geometry} material={materials['Material.047']} />
          <mesh name="Sphere011_1" geometry={nodes.Sphere011_1.geometry} material={materials['Material.049']} />
          <mesh name="Sphere011_2" geometry={nodes.Sphere011_2.geometry} material={materials['Material.053']} />
          <mesh name="Sphere011_3" geometry={nodes.Sphere011_3.geometry} material={materials['Material.054']} />
          <mesh name="Sphere011_4" geometry={nodes.Sphere011_4.geometry} material={materials['Material.055']} />
          <mesh name="Sphere011_5" geometry={nodes.Sphere011_5.geometry} material={materials['Material.056']} />
          <mesh name="Sphere011_6" geometry={nodes.Sphere011_6.geometry} material={materials['Material.057']} />
          <mesh name="Sphere011_7" geometry={nodes.Sphere011_7.geometry} material={materials['Material.058']} />
          <mesh name="Sphere011_8" geometry={nodes.Sphere011_8.geometry} material={materials['Material.059']} />
          <mesh name="Sphere011_9" geometry={nodes.Sphere011_9.geometry} material={materials['Material.060']} />
          <mesh name="Sphere011_10" geometry={nodes.Sphere011_10.geometry} material={materials['Material.061']} />
          <mesh name="Sphere011_11" geometry={nodes.Sphere011_11.geometry} material={materials['Material.062']} />
          <mesh name="Sphere011_12" geometry={nodes.Sphere011_12.geometry} material={materials['Material.063']} />
          <mesh name="Sphere011_13" geometry={nodes.Sphere011_13.geometry} material={materials['Material.064']} />
          <mesh name="Sphere011_14" geometry={nodes.Sphere011_14.geometry} material={materials['Material.065']} />
          <mesh name="Sphere011_15" geometry={nodes.Sphere011_15.geometry} material={materials['Material.066']} />
        </group>
      </group>
    </group>
  )
}

export default Yucca

useGLTF.preload('/models/yucca.glb')
